### ISSUE TITLE
[Feature Request] Make sure to add customization only to the specific actor, instead of globally.

### ISSUE THREAD

**Issue by p4535992** [misthero/dnd5e-custom-skills#19]
The use case is simple I want to be able to add specific skills to the specific actor, to be able to differentiate things like training in something and other stuff.

**Comment by misthero** [comment]
hello sorry for the late response, you know, real life called.

that is a little out of the scope of this module, not mentioning it would need a good rewrite of the code since the skills are global by default in the system, you can be proficient or not proficient in one skill or another, but you always see every available skill in the system.

what I can suggest is just, add every skill you need and every player will use or ignore some of them, like in core anyway.

**Comment by p4535992** [comment]
kk no worries ty for the response!
